# Use postgres/example user/password credentials
version: '16.0'
volumes:
  volume-fastapi:
    driver: local
    driver_opts:
      type: none
      device: ./app
      o: bind
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin_postgresql
      POSTGRES_PASSWORD: admin01
    ports:
      - 5432:5432
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    volumes: 
      - "volume-fastapi:/usr/src/app" 
    image: "app:clima"
    build:
      context: ./app
    links:
      - db
    command:
      uvicorn --host 0.0.0.0 main:app --reload
    ports:
      - 8000:8000