# Use postgres/example user/password credentials
version: '16.0'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin_postgresql
      POSTGRES_PASSWORD: admin01
    ports:
      - 5454:5454
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    image: "app:clima"
    build: ./Clima_app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    restart: always
    ports:
      - 8000:8000
